name: youtube_video_webview
description: "A customizable YouTube video player for Flutter, supporting embedded playback, fullscreen mode, sharing, captions, and seamless redirection to YouTube inside a webview."
version: 1.0.2
repository: "https://github.com/mclaramarinho/youtube-video-webview-lib"

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  share_plus: ^12.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0